---
include:
  - board: seeeduino_xiao_ble
    shield: horangi_78_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: horangi_78_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset